[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 921600  ; = SERIAL_BAUD en config.h

; Neural_Networks_FF y Dynamic_Array son librerías locales en lib/
lib_deps = 
    jrowberg/i2cdevlib-MPU6050
    bblanchon/ArduinoJson@^7.2.0
    esp32async/ESPAsyncWebServer@^3.12.1

lib_ignore = 
    RPAsyncTCP

lib_ldf_mode = deep+

build_unflags = -Werror
